# Generated by Django 4.0 on 2022-11-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aql_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Не заблокирован'), (False, 'Заблокирован')], default=False, verbose_name='Статус доступа'),
        ),
    ]
