# Generated by Django 4.0 on 2022-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aql_user', '0003_rename_username_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Почта подтверждена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Не заблокирован'), (False, 'Заблокирован')], default=True, verbose_name='Статус доступа'),
        ),
    ]
