# Generated by Django 4.0 on 2022-11-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aql_user', '0004_user_is_email_confirmed_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/users/avatar/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(2, 'COURSEOWNER'), (1, 'SUPERADMIN'), (3, 'REGULAR')], default=3, verbose_name='Роль'),
        ),
    ]
